version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/mcp-server
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs
    networks:
      - mcp-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mcp-network

volumes:
  mongo-data:

networks:
  mcp-network:
    driver: bridge